[package]
name = "protobot_sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking"] }
base64 = "0.13.0"
ed25519-dalek = "1.0.1"
